name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:


  build:

    runs-on: ubuntu-latest

    steps:
     - name: login to docker hub
       uses: actions/checkout@v3

     - name: login to docker hub
       run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
       
     - name: build docker image
       run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/overflow_reality:update




